/**
 * Author......: Gabriele "matrix" Gristina
 * License.....: MIT
 *
 * A PCFG trainer.
 */

#ifndef PCFG_COMMON_H
#define PCFG_COMMON_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>

/* The trainer's own version; the ruleset format has its own, in config.ini. */
#define HP_VERSION "1.0"

/* What a reader can carry, mirrored from hashcat's feed so the two agree. */
#define PCFG_MAXSLOT 48

/* And the longest candidate anything will emit. */
#define PCFG_MAXPWLEN 256

#define PCFG_MAXLINE 65536  /* longest line, and longest value */
#define PCFG_MAXSECTIONS 64 /* sections one password may decompose into */
#define PCFG_MAXTYPE 16     /* a type string, "A12" */
#define PCFG_MAXPATH 4096

/* pcfg_token_t types, first character of the type string: Weir's alphabet, which
 * the three readers decode as Weir does. */
#define PCFG_ST_ALPHA 'A'
#define PCFG_ST_DIGIT 'D'
#define PCFG_ST_OTHER 'O'
#define PCFG_ST_YEAR 'Y'
#define PCFG_ST_CONTEXT 'X'
#define PCFG_ST_KEYBOARD 'K'
#define PCFG_ST_EMAIL 'E'
#define PCFG_ST_WEBSITE 'W'
#define PCFG_ST_CASE 'C'
#define PCFG_ST_MARKOV 'M'
#define PCFG_ST_UNTYPED '\0'

/* Types the trainer keeps for itself: they name no list a reader looks for. */
#define HP_TY_PRINCE 'p'   /* what each section was, as a type */
#define HP_TY_RAW 'r'      /* the base structure with E and W kept */
#define HP_TY_WEBPFX 'q'   /* the http:// or www. a URL came with */
#define HP_TY_FULLMAIL 'e' /* the whole address, only with --save-sensitive */
#define HP_TY_FULLURL 'u'  /* the whole URL, only with --save-sensitive */

/* One parsed segment of a password. `value` points into the password buffer. */
typedef struct
{
  char *value;
  int vlen;
  int cp_len;
  char type[PCFG_MAXTYPE];
} pcfg_token_t;

/* Unicode category tables, generated by tools/gen_unicode_tables.go from Go's own
 * - the same ones pcfg-go asks through unicode.IsLetter. */
typedef struct
{
  uint32_t lo, hi;
} hp_range_t;

typedef struct
{
  uint32_t from, to;
} hp_casemap_t;

extern const hp_range_t hp_letter_ranges[];
extern const size_t hp_letter_ranges_cnt;
extern const hp_range_t hp_digit_ranges[];
extern const size_t hp_digit_ranges_cnt;
extern const hp_range_t hp_upper_ranges[];
extern const size_t hp_upper_ranges_cnt;
extern const hp_casemap_t hp_tolower_map[];
extern const size_t hp_tolower_map_cnt;
extern const hp_casemap_t hp_toupper_map[];
extern const size_t hp_toupper_map_cnt;

int utf8_decode (const char *s, int len, uint32_t *cp);
int utf8_encode (char *buf, uint32_t cp);
int utf8_cplen (const char *s, int bytelen);
int utf8_is_alpha (uint32_t cp);
int utf8_is_digit (uint32_t cp);
int utf8_is_upper (uint32_t cp);
uint32_t utf8_to_lower (uint32_t cp);
uint32_t utf8_to_upper (uint32_t cp);

typedef struct hp_mem
{
  int64_t budget; /* this pool's own ceiling, 0 = none of its own */
  int64_t used;
  struct hp_mem *parent; /* the total everything draws on, NULL at the top */
} hp_mem_t;

/* A pool with no parent is the whole ceiling; one with a parent has a share. The
 * word set and the OMEN contexts each get one: they run first and never shrink. */
void hp_mem_init (hp_mem_t *m, size_t budget);
void hp_mem_share (hp_mem_t *m, hp_mem_t *parent, size_t cap);
bool hp_mem_take (hp_mem_t *m, size_t bytes);
void hp_mem_give (hp_mem_t *m, size_t bytes);
int64_t hp_mem_used (const hp_mem_t *m);

int hp_fclose_w (FILE *f, const char *path);

const char *hp_group (int64_t v, char *out, size_t n);
void hp_bar_block (char *buf, size_t buf_size, double percentage, int width);

typedef struct pcfg_words pcfg_words_t;

extern pcfg_words_t *hp_words;

pcfg_words_t *pcfg_multiword_init (int threshold, int min_len, int max_len);
void pcfg_multiword_destroy (pcfg_words_t *mw);
void pcfg_multiword_train (pcfg_words_t *mw, const char *pw, int pwlen, int64_t n);
void pcfg_multiword_set_readonly (pcfg_words_t *mw);
void pcfg_multiword_pretrain (pcfg_words_t *mw, bool on);
void pcfg_multiword_threaded (pcfg_words_t *mw, bool on);
void pcfg_multiword_account (pcfg_words_t *mw, hp_mem_t *mem);
int pcfg_multiword_save (pcfg_words_t *mw, const char *path, int64_t min_count);
int pcfg_multiword_parse (pcfg_words_t *mw, const char *alpha, int alen, int *parts, int max_parts);

typedef struct
{
  int start;
  int len;
} pcfg_kb_walk_t;

int pcfg_keyboard_walks (const char *pw, int pwlen, pcfg_kb_walk_t *walks, int max_walks);

/* What the email and website passes took apart, which the sections do not carry:
 * the provider after the '@', the host of a URL, and the "http://www." it came
 * with. Zero length means the pass found nothing; pass NULL to be told nothing. */
typedef struct
{
  char provider[256];
  int provlen;
  char host[256];
  int hostlen;
  char prefix[64];
  int pfxlen;
} hp_seen_t;

/* Whether every token of a structure finds a slot in a reader. */
bool hp_structure_fits (const pcfg_token_t *sects, int nsects);

int pcfg_tokenize (char *pw, int pwlen, pcfg_token_t *sects, int maxsects, unsigned char *tag, char *lower, hp_seen_t *seen);
void build_case_mask (const char *alpha, int bytelen, char *mask);
void build_base_structure (pcfg_token_t *sects, int nsects, char *out, int outlen);

/* The structure as parsed, E and W included. Written to raw_grammar.txt, a record
 * of the training set rather than an input to guessing. */
void build_raw_structure (pcfg_token_t *sects, int nsects, char *out, int outlen);

typedef struct hp_store hp_store_t;

hp_store_t *hp_store_new (int nshard, size_t arena_block);
void hp_store_free (hp_store_t *st);
void hp_store_limit (hp_store_t *st, size_t budget, int admit, size_t filter_bytes);
void hp_store_account (hp_store_t *st, hp_mem_t *m);
int64_t hp_store_refused (const hp_store_t *st);
void hp_store_threaded (hp_store_t *st, bool on);
bool hp_store_is_full (const hp_store_t *st);
void hp_store_add (hp_store_t *st, uint8_t type, uint8_t len, const char *val, int vlen, int64_t n);
int64_t hp_store_get (const hp_store_t *st, uint8_t type, uint8_t len, const char *val, int vlen);
int64_t hp_store_count (const hp_store_t *st);
size_t hp_store_bytes (const hp_store_t *st);
size_t pcfg_multiword_bytes (const pcfg_words_t *mw);
int64_t hp_store_entries (const hp_store_t *st);

/* Walk every entry of one (type, length), for the writer. */
typedef void (*hp_store_fn) (const char *val, int vlen, int64_t cnt, void *arg);
typedef void (*hp_store_all_fn) (uint8_t type, uint8_t len, const char *val, int vlen, int64_t cnt, void *arg);

int64_t hp_store_total (const hp_store_t *st, uint8_t type, uint8_t len);
void hp_store_foreach (const hp_store_t *st, uint8_t type, uint8_t len, hp_store_fn fn, void *arg);
void hp_store_foreach_all (const hp_store_t *st, hp_store_all_fn fn, void *arg);

#endif /* PCFG_COMMON_H */
