// Emits src/pcfg_unicode_tables.c from Go's tables.
//
// The classification has to agree with pcfg-go, which uses unicode.IsLetter and
// unicode.IsDigit, so the tables are generated from those same functions rather
// than from hand-written ranges or a second Unicode library.
//
// The agreement holds at the version the tables were generated at, and Go's own
// move with its releases: a pcfg-go built against a newer toolchain classifies
// codepoints this does not. The generated file names the version it carries, so
// the two can be compared; regenerating is a deliberate change to the model and
// not a refresh.
//
//	cd tools && go run gen_unicode_tables.go > ../src/pcfg_unicode_tables.c
//
// The result is committed, so building needs neither Go nor Python.
package main

import (
	"fmt"
	"os"
	"runtime"
	"strings"
	"unicode"
)

const maxCP = 0x110000

// The whole file, so the blank line the last table leaves can be trimmed.
var out strings.Builder

func ranges(pred func(rune) bool) [][2]rune {
	var out [][2]rune
	start := rune(-1)
	for cp := rune(0); cp < maxCP; cp++ {
		if pred(cp) {
			if start < 0 {
				start = cp
			}
		} else if start >= 0 {
			out = append(out, [2]rune{start, cp - 1})
			start = -1
		}
	}
	if start >= 0 {
		out = append(out, [2]rune{start, maxCP - 1})
	}
	return out
}

func emitRanges(name string, rs [][2]rune) {
	fmt.Fprintf(&out, "const hp_range_t %s[] = {\n", name)
	for _, r := range rs {
		fmt.Fprintf(&out, "  { 0x%04X, 0x%04X },\n", r[0], r[1])
	}
	fmt.Fprintf(&out, "};\n\nconst size_t %s_cnt = %d;\n\n", name, len(rs))
}

func emitMap(name string, f func(rune) rune) {
	type pair struct{ from, to rune }
	var ps []pair
	for cp := rune(0x80); cp < maxCP; cp++ {
		if to := f(cp); to != cp {
			ps = append(ps, pair{cp, to})
		}
	}
	fmt.Fprintf(&out, "const hp_casemap_t %s[] = {\n", name)
	for _, p := range ps {
		fmt.Fprintf(&out, "  { 0x%04X, 0x%04X },\n", p.from, p.to)
	}
	fmt.Fprintf(&out, "};\n\nconst size_t %s_cnt = %d;\n\n", name, len(ps))
}

func main() {
	fmt.Fprintln(os.Stderr, "generated by tools/gen_unicode_tables.go")
	fmt.Fprintln(&out, "/**")
	fmt.Fprintln(&out, " * Author......: Gabriele \"matrix\" Gristina")
	fmt.Fprintln(&out, " * License.....: MIT")
	fmt.Fprintln(&out, " *")
	fmt.Fprintln(&out, " * GENERATED by tools/gen_unicode_tables.go - do not edit by hand.")
	fmt.Fprintln(&out, " *")
	fmt.Fprintln(&out, " * Unicode category ranges taken from Go's tables, which are what pcfg-go")
	fmt.Fprintln(&out, " * asks through unicode.IsLetter and unicode.IsDigit.")
	fmt.Fprintln(&out, " *")
	fmt.Fprintf(&out, " * Unicode %s, from %s. Go's tables move with its releases, so\n", unicode.Version, runtime.Version())
	fmt.Fprintln(&out, " * regenerating against a newer toolchain reclassifies codepoints and changes")
	fmt.Fprintln(&out, " * what the trainer counts. That is a decision, not a refresh.")
	fmt.Fprintln(&out, " */")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "#include \"pcfg_common.h\"")
	fmt.Fprintln(&out)
	emitRanges("hp_letter_ranges", ranges(unicode.IsLetter))
	emitRanges("hp_digit_ranges", ranges(unicode.IsDigit))
	emitRanges("hp_upper_ranges", ranges(unicode.IsUpper))
	emitMap("hp_tolower_map", unicode.ToLower)
	emitMap("hp_toupper_map", unicode.ToUpper)

	/* The last table leaves a blank line behind it, which the file does not want. */
	fmt.Print(strings.TrimRight(out.String(), "\n") + "\n")
}
